---
title: "Mazurka paper figures"
author: "DJM"
date: "2/22/2019"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE, results='hide'}
library(dpf)
library(knitr)
library(splines)
opts_chunk$set(message=FALSE, warning=FALSE, cache=TRUE, 
               autodep = TRUE, echo=FALSE,
               #out.width ="6in",out.height="3in",
               fig.path = 'gfx/',
               fig.width = 6, fig.height = 3, 
               fig.align = 'center')
library(gplots)
library(tidyverse)
library(heatmaply)
load("../extras/mazurkaResultsNoVar2.Rdata") 
source("dirichlet_precision.R")

pvec_ml = pvec_ml %>% select(-value,-fevals,-gevals,-convergence) %>%
  data.matrix %>% data.frame
# remove Block
# bad = which(rownames(pvec_ml)=="Block_1995")
# pvec_ml = pvec_ml[-bad,]
theme_set(theme_minimal(base_family="Times"))
data(tempos)
lt = diff(c(tempos$note.onset,61))
library(RColorBrewer)
fivecolors = viridis(5, option='plasma',begin=.2)[c(1,4,2,5,3)] #brewer.pal(5,'Set1')[c(2,1,3,5,4)]
library(dendextend)
```



# Short tempo figure

```{r small-rubinstein-1961,out.width="5in", out.height="2in", fig.width=7.5,fig.height=3}
ggplot(tempos, aes(x=note_onset, y=Rubinstein_1961)) +
  geom_line() + ylab('tempo (bpm)') + xlab('measure') +
  scale_x_continuous(breaks=1:4*2, limits = c(1,9)) +
  #geom_vline(xintercept = c(1,8.9,9)) +
  # coord_cartesian(xlim=c(1,9-1e-6)) +
  geom_hline(yintercept = 132, linetype='dashed')
```

# Comparing clusters

```{r clustering-processing}
perfs = tempos[,-c(1:3)] %>% as.matrix %>% t
row.names(pvec_ml) = sub('_',' ',row.names(pvec_ml))
hc_parm = pvec_ml %>% Dmats %>% Reduce(f='+')
row.names(hc_parm) = row.names(pvec_ml)
hc_perf = perfs %>% dist %>% percentize %>% hclust

dend_parm = hc_parm %>% as.dist %>% hclust %>% as.dendrogram
dend_perf = hc_perf %>% as.dendrogram
```



## Distance matrix from parameters

```{r parametric-clusters,fig.width=4,fig.height=4,out.width="3in",out.height="3in"}
#hc_parm = hc_parm+diag(1e-12,nrow(hc_parm))
subs = apply(hc_parm,1,quantile,probs=4/46) < .35#.45
#subs = rowMeans(hc_parm) < .95#.968
sDmat = hc_parm[subs,subs]
nclusts = 4
colorthem = TRUE
heatmap.2(
  hc_parm, Rowv = dend_parm, Colv = dend_parm, 
  symm=TRUE,
  dendrogram = 'none',
  density.info = 'none', trace='none',
          #labRow = TRUE,
  labCol = NA,
  key.title = NA,
  col= viridis,#colorRampPalette(c('#0b61a4','white')),
  key.xlab = NA, 
  margins = c(1,6),
  cexRow = .6,
  cexCol = .6,
  lhei=c(1,15),
  lwid=c(1,15),
  offsetCol = 0, offsetRow = 0,
  key=FALSE
)
sdends = sDmat %>% as.dist %>% hclust %>% as.dendrogram
if(colorthem) sdends = sdends %>% 
  set('labels_col', value=fivecolors[c(4,3,1,2)], k=nclusts) %>%
  set('branches_lty', 1) %>%
  set('branches_k_color', value=fivecolors[c(4,3,1,2)], k=nclusts)
heatmap.2(sDmat,
          Rowv = sdends, Colv = sdends,
          symm=TRUE,
          density.info = 'none', trace='none',
          #labRow = TRUE,
          labCol = NA,
          key.title = NA,
          col=viridis,#colorRampPalette(c('#0b61a4','white')),
          key.xlab = NA, 
          margins = c(1,6),
          cexRow = .6,
          cexCol = .6,
          lhei=c(1,8),
          lwid=c(1,8),
          offsetCol = 0, offsetRow = 0,
          key=FALSE
)

clustered = data.frame(clust = as.factor(cutree(as.hclust(sdends), k = nclusts)),
                 performer = row.names(sDmat))
pvec_all = pvec_ml %>% data.matrix %>% data.frame
pvec_all$performer = row.names(pvec_ml)
row.names(pvec_all) = NULL
pvec_all = full_join(pvec_all, clustered)
levels(pvec_all$clust) = c(levels(pvec_all$clust),'other')
pvec_all$clust[is.na(pvec_all$clust)] = 'other'
```

## Distance matrix from raw data

```{r raw-data-clusters,fig.width=4,fig.height=4,out.width="3in",out.height="3in"}
heatmap.2(as.matrix(percentize(dist(perfs))),
          Rowv = dend_perf, Colv = dend_perf, 
          symm=TRUE,
          density.info = 'none', trace='none',
          labRow = sub('_',' ',row.names(pvec_ml)),
          labCol = NA,
          key.title = NA,
          col=viridis,#colorRampPalette(c('#0b61a4','white')),
          key.xlab = NA, 
          margins = c(1,6),
          cexRow = .6,
          cexCol = .6,
          lhei=c(1,8),
          lwid=c(1,8),
          offsetCol = 0, offsetRow = 0,
          key=FALSE
)

```

# Cluster densities

```{r clust-densities, fig.height=8,fig.width=6.5}
lab_lookup = c("sigma[epsilon]^2", "mu[tempo]",
               "mu[acc]", "mu[stress]", "sigma[tempo]^2",
               "p[1*','*1]", "p[1*','*2]", "p[3*','*1]","p[1*','*3]",
               "p[2*','*1]","p[3*','*2]","p[2*','*2]")
               #sig2acc="sigma^2[acc]",sig2stress="sigma^2[stress]"
               #)
ttt = pvec_all %>% gather(key='parameter',value='value',-clust,-performer)
ttt$parameter = factor(ttt$parameter,levels=unique(ttt$parameter),
                       labels= lab_lookup)
ttt %>%
  ggplot(aes(x=value, fill=clust)) +
  geom_density(alpha=.75,adjust=1.75) +
  facet_wrap(~parameter,scales='free',
             labeller = label_parsed) +
  scale_fill_manual(values=fivecolors[1:(nclusts+1)]) + xlab('') +
  theme(legend.title = element_blank(), legend.position = 'bottom')
```

```{r clust-densities-sub1, fig.height=4,fig.width=8}
ttt %>% filter(parameter %in% lab_lookup[1:5],
               clust != 'other') %>%
  ggplot(aes(x=value, fill=clust)) +
  geom_density(alpha=.75,adjust=1.75) +
  facet_wrap(~parameter,scales='free',
             labeller = label_parsed, nrow=1) +
  scale_fill_manual(values=fivecolors[1:(nclusts+1)]) + xlab('') +
  theme(legend.title = element_blank(), legend.position = 'bottom')
```

```{r clust-densities-sub2, fig.height=6.5,fig.width=8}
ttt %>% filter(parameter %in% lab_lookup[6:12],
               clust != 'other') %>%
  ggplot(aes(x=value, fill=clust)) +
  geom_density(alpha=.75,adjust=1.75) +
  facet_wrap(~parameter,scales='free',
             labeller = label_parsed, nrow=2) +
  scale_fill_manual(values=fivecolors[1:(nclusts+1)]) + xlab('') +
  theme(legend.title = element_blank(), legend.position = 'bottom')
```


# Plotting performances

```{r all-perfs, fig.width=6.5,fig.height=9}
plots = vector("list", 4)
lt = diff(c(tempos$note_onset, 61))
for(i in 1:nrow(pvec_ml)){
  params = unlist(pvec_ml[i,])
  y = matrix(tempos[,gsub(' ','_',row.names(pvec_ml)[i])], nrow = 1)
  pmats = musicModel(lt, params[1], params[2:4], c(params[5],1,1),
                     params[6:12], c(132,0), c(400,10))
  beam = beamSearch(pmats$a0, pmats$P0, c(1,0,0,0,0,0,0,0,0,0), 
                    pmats$dt, pmats$ct, pmats$Tt, pmats$Zt,
                    pmats$HHt, pmats$GGt, y, pmats$transMat, 400)
  bestpath = beam$paths[which.max(beam$weights),]
  kal = kalman(pmats, bestpath, y)
  plots[[i]] = data.frame(measure = tempos$note_onset, tempo = c(y), 
                  inferred = c(kal$ests), state = convert10to4(bestpath))
}
plots = bind_rows(plots)
plots$performer = rep(pvec_all$performer, each=length(y))
plots$clust = rep(pvec_all$clust, each=length(y))
plots$state = as.factor(plots$state) 
plots = plots %>% mutate(
  state=factor(state,labels=c('constant','decel','accel','stress'))
  )
perfcols = viridis_pal(begin=.2)(nlevels(plots$state))
# plots$pointx = 10
# plots$pointy = 400
# deunderscore = function(x) gsub('_',' ',x)
```

## Cluster 1

```{r clust-1, fig.height=9, fig.width=6}
perfshapes = c(16,17,15,3)
ggplot(filter(plots, clust=='1')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state, shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols[c(1,2,4)]) +
  scale_shape_manual(values=perfshapes[c(1,2,4)]) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,ncol=3) #+
```

## Cluster 2

```{r clust-2, fig.height=9, fig.width=6}
ggplot(filter(plots, clust=='2')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state, shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols)+#[c(1,2,4)]) +
  scale_shape_manual(values=perfshapes)+#[c(1,2,4)]) +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,ncol = 3) #+
```

## Cluster 3

```{r clust-3, fig.height=9, fig.width=6}
ggplot(filter(plots, clust=='3')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols[c(1,2,4)]) +
  scale_shape_manual(values=perfshapes[c(1,2,4)]) +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,ncol=3) #+
```

## Cluster 4

```{r clust-4, eval=TRUE, fig.height=9, fig.width=6}
ggplot(filter(plots, clust=='4')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols)+#[c(1,2,4)]) +
  scale_shape_manual(values=perfshapes)+#[c(1,2,4)]) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,ncol=3) #+
```

## Cluster "other"

```{r clust-other, fig.height=9, fig.width=6}
ggplot(filter(plots, clust=='other')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,ncol=3) #+
```



## Individual performances


```{r richter}
ggplot(filter(plots, performer == 'Richter 1976')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
 # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer) #+
  # geom_point(aes(x=pointx,y=pointy,color=clust),alpha=.5, size=5, shape=15) + 
  # scale_color_manual(values = fivecolors)
```

```{r hatto}
ggplot(filter(plots, performer == 'Hatto 1993')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols[c(1,2)]) +
  scale_shape_manual(values=perfshapes[c(1,2)]) +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer) #+
  # geom_point(aes(x=pointx,y=pointy,color=clust),alpha=.5, size=5, shape=15) + 
  # scale_color_manual(values = fivecolors)
```

```{r cortot-performance}
ggplot(filter(plots, performer == 'Cortot 1951')) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols[c(1,3,4)]) +
  scale_shape_manual(values=perfshapes[c(1,3,4)]) +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer) #+
  # geom_point(aes(x=pointx,y=pointy,color=clust),alpha=.5, size=5, shape=15) + 
  # scale_color_manual(values = fivecolors)
```

```{r two-performances,fig.height=4}
filter(plots, performer %in% c('Richter 1976','Hatto 1993')) %>%
  ggplot() + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state, shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,nrow = 1) #+
  # geom_point(aes(x=pointx,y=pointy,color=clust),alpha=.5, size=5, shape=15) + 
  # scale_color_manual(values = fivecolors)
```

## Parameter table

```{r two-perfs-parameters}
kable(pvec_ml[c('Richter 1976','Hatto 1993','Cortot 1951'),],
      digits = 2, format = 'latex')
```



# Different smoothing

Try splines, replicating knots, l1tf?

```{r alternative-smoothers}
nsplines = 64 # 1 knot per bar plus boundary
B = bs(tempos$note_onset, df=nsplines, intercept = TRUE)
single.knots = match(seq(4,56,by=4)+1,tempos$meas_num)
double.knots = match(c(16,24,32,44)+1, tempos$meas_num)
triple.knots = match(c(16,24,32,44)+1, tempos$meas_num)
quad.knots = match(c(16,24,32,44)+1, tempos$meas_num)
all.knots = tempos$note_onset[
  sort(c(single.knots,double.knots,triple.knots,quad.knots))]
B1 = bs(tempos$note_onset, knots = all.knots, intercept = TRUE,Boundary.knots = c(1,61))

spline_music = plots %>% group_by(performer) %>% 
  mutate(preds_smooth = fitted(lm(tempo~B-1)), 
         preds_music = fitted(lm(tempo~B1-1)))
filter(spline_music , performer %in% c('Richter 1976')) %>%
  gather(key='key',value = 'value', -tempo, 
         -measure, -state, -performer, -clust) %>%
  ggplot() + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90', show.legend = FALSE) +
  geom_point(aes(x=measure, y=tempo), color='gray40', show.legend = FALSE) +
  geom_line(aes(x=measure, y=value, color=key)) + 
  scale_color_viridis_d(option = 'plasma',
                        labels=c('music model','musical spline','regression spline')) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,nrow=2) #+
  # geom_rect(aes(xmin=pointx-2.5, xmax=pointx+2.5,
  #               ymin=pointy-2.5,ymax=pointy+2.5,fill=clust), 
  #           show.legend = FALSE,
  #            alpha=.5,size=5) + 
  # scale_fill_manual(values = fivecolors) 
```




# Similar performances 

```{r similar-perfs,fig.height=6}
similar = c('Wasowski 1980','Shebanova 2002','Luisada 1991','Milkina 1970')
ggplot(filter(plots, performer %in% similar)) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols) +
  theme(legend.position = 'bottom', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,nrow=2) #+
  # geom_point(aes(x=pointx,y=pointy,color=clust),alpha=.5, size=5, shape=15) + 
  # scale_color_manual(values = fivecolors)
```

# Rubinstein contrast

```{r rubinstein-perfs, fig.height=6}
similar = c('Rubinstein 1939', 'Rubinstein 1952',
            'Rubinstein 1961','Rubinstein 1966')
ggplot(filter(plots, performer %in% similar)) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state,shape=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols) +
  theme(legend.position = 'none', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer,nrow=2) #+
  # geom_point(aes(x=pointx,y=pointy,color=clust),alpha=.5, size=5, shape=15) + 
  # scale_color_manual(values = fivecolors)
```

```{r similar-rubin-parameters}
kable(pvec_ml[c(
  'Wasowski 1980','Shebanova 2002','Luisada 1991','Milkina 1970',
  'Rubinstein 1939', 'Rubinstein 1952',
  'Rubinstein 1961','Rubinstein 1966'),],
      digits = 2, format = 'latex')
```


# Bad estimation

```{r bad-model}
ggplot(filter(plots, performer %in% c('Barbosa 1983','Fou 1978'))) + 
  geom_rect(data=data.frame(xmin = 33, xmax = 45, ymin = -Inf, ymax = Inf),
              aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),
              fill = 'gray90', color = 'gray90') +
  geom_line(aes(x=measure, y=tempo), color='gray40') +
  geom_point(aes(x=measure, y=inferred, color=state)) +
  # scale_color_brewer(palette='Set1') +
  scale_color_manual(values=perfcols) +
  theme(legend.position = 'none', legend.title = element_blank(),
        strip.text = element_text(hjust = 0)) +
  facet_wrap(~performer)
```
