# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resampleSubOptimal <- function(w, N) {
    .Call('_dpf_resampleSubOptimal', PACKAGE = 'dpf', w, N)
}

resampleOptimal <- function(w, N) {
    .Call('_dpf_resampleOptimal', PACKAGE = 'dpf', w, N)
}

kf1stepR <- function(a0, P0, dt, ct, Tt, Zt, HHt, GGt, yt) {
    .Call('_dpf_kf1stepR', PACKAGE = 'dpf', a0, P0, dt, ct, Tt, Zt, HHt, GGt, yt)
}

dpf <- function(currentStates, w, N, transProbs, a0, P0, dt, ct, Tt, Zt, HHt, GGt, yt) {
    .Call('_dpf_dpf', PACKAGE = 'dpf', currentStates, w, N, transProbs, a0, P0, dt, ct, Tt, Zt, HHt, GGt, yt)
}

#' Evaluate the likelihood given parameters and discrete states
#' 
#' @param pmats a list of parameter matrices for the kalman filter. This can either be the output of yupengMats, or a list with the same names as the output of yupengMats.
#' @param path vector giving the desired path for hidden discrete states
#' @param y observations, each time point in a column
#' 
#' @return the negative log-likelihood
#' 
#' @export 
getloglike <- function(pmats, path, y) {
    .Call('_dpf_getloglike', PACKAGE = 'dpf', pmats, path, y)
}

#' Create parameter matrices as in Gu (2017)
#' 
#' @param lt durations between successive notes in the score
#' @param sig2eps variance of the observation noise
#' @param mus vector of 3 mean parameters
#' @param sig2eta vector of 3 state variance parameters
#' @param transprobs vector of 4 transition probabilities
#' 
#' @return List with components as appropriate for Kalman filtering or Beam Search
#' 
#' @export    
yupengMats <- function(lt, sig2eps, mus, sig2eta, transprobs, initialMean, initialVariance) {
    .Call('_dpf_yupengMats', PACKAGE = 'dpf', lt, sig2eps, mus, sig2eta, transprobs, initialMean, initialVariance)
}

#' Greedy HMM estimation given continuous hidden states
#' 
#' @param a0 a px1 matrix of state prior means
#' @param P0 a pxp matrix of state
#' @param dt dx1 or dxn matrix of 
#' 
#' @return List with components "paths", "weights", and "LastStep" 
#' 
#' @export 
beamSearch <- function(a0, P0, w0, dt, ct, Tt, Zt, HHt, GGt, yt, transProbs, N) {
    .Call('_dpf_beamSearch', PACKAGE = 'dpf', a0, P0, w0, dt, ct, Tt, Zt, HHt, GGt, yt, transProbs, N)
}

#' Estimate continuous states given parameters and discrete hidden states
#' 
#' @param pmats e.g., as output from yupengMats
#' @param path path of discrete hidden states
#' @param y observations
#' 
#' @return List with components from Kalman filter and Smoother
#' 
#' @export 
kalman <- function(pmats, path, y) {
    .Call('_dpf_kalman', PACKAGE = 'dpf', pmats, path, y)
}

